FROM golang:1.27.0-alpine3.24

RUN apk add --no-cache gcc musl-dev

ENV GOPROXY=https://goproxy.cn,direct

RUN go install github.com/air-verse/air@v1.67.4

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8000

CMD ["air"]
