FROM golang:1.25-alpine

RUN apk add --no-cache gcc musl-dev

ENV GOPROXY=https://goproxy.cn,direct

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8000

CMD ["air"]
